feat: Add implementation for Orange & Rockland Utilities
tronikos/opower pull request #42
Opened 2023-08-22 23:35 UTC by bvlaicu

2023-08-23 02:34 UTC, tronikos requested changes

2023-08-25 01:57 UTC, bvlaicu commented on src/opower/utilities/oru.py
Makes sense. Done. Thanks.

2023-08-25 01:58 UTC, bvlaicu commented on src/opower/utilities/oru.py
> +        return "Orange & Rockland Utilities (Oru)"
Correct. Done.

2023-08-25 07:02 UTC, tronikos requested changes

2023-08-25 07:02 UTC, tronikos commented on src/opower/utilities/oru.py
> +HOSTNAME = "oru.com"
I don't see how this overrides the one in coned.py. Have you tested your latest revision still works? If it does then I guess you can login to coned.com with oru.com credentials in which case you don't need any changes in coned.py and just go with your changes below. If it doesn't work, you have to extract the hostname to a static method and override it below.

2023-08-25 07:02 UTC, tronikos commented on src/opower/utilities/oru.py
> +class Oru(ConEd, UtilityBase):
You shouldn't need to extend UtilityBase since ConEd already extends it.

2023-08-25 07:12 UTC, tronikos commented on src/opower/utilities/oru.py
> +HOSTNAME = "oru.com"
You will have to change only in coned.py:

from

```python
    @staticmethod
    async def async_login(
        session: aiohttp.ClientSession,
```
to:

```python
    @classmethod
    async def async_login(
        cls,
        session: aiohttp.ClientSession,
```

and then inside async_login you will be able to reference the @staticmethod that returns the hostname with: `cls.hostname()`

This also means some of the constants in coned.py will have to become variables in async_login.

2023-08-26 07:53 UTC, tronikos commented
I committed https://github.com/tronikos/opower/commit/a580b15953b5355ef41ebc2f507a53ffc1ffee2c with your changes plus my suggestions. Thanks!

2023-08-26 07:53 UTC, closed without merging

2023-08-26 13:39 UTC, bvlaicu commented
Oh, thanks, I just committed my changes then saw your updates. They are very similar, anyway.
And regarding testing my previous version, yes, I tested it so yes, you can log into coned with oru creds. Which I kind of knew from other past experiments if I think about it now.
Thanks for all your work.