WIP: Add Portland General Electric PGN to utilities
tronikos/opower pull request #44
Opened 2023-09-07 00:47 UTC by jrigling

Hello. This PR add Portland General Electric, which is available in many parts of Oregon. Portland General is often referred to as PGE, so I just want to point out that is confusing with Pacific Gas & Electric and already used. I've use PGN here since that is the opower subdomain.

There are several "secret" keys used in the flow that I learned from another python project. They are hidden in the login page. Should this be developed like the pge.py that scrapes those from the login page?

I also need to confirm that the error conditions work properly (that failed logins produce useful error messages), but I wanted to get this draft PR in for comments.

2023-09-07 06:55 UTC, tronikos requested changes
If what you have is working this is ready to merge after addressing my 2 comments. Thanks!

2023-09-07 06:55 UTC, tronikos commented on src/opower/utilities/portlandgeneral.py
> +class PGN(UtilityBase):
All the other utilities have a filename and class name that matches the utility website. Use PortlandGeneral here.

2023-09-07 06:55 UTC, tronikos commented on src/opower/utilities/portlandgeneral.py
> +import urllib.parse
Seems unused. Run `isort . ; black . ; flake8 . ; ruff . --fix ; mypy --install-types .`

2023-09-07 07:05 UTC, tronikos commented on README.md
> +- Portland General Electric (PGE)
keep the list sorted

2023-09-13 02:38 UTC, tronikos commented
Will you be able to address my commends soon so that I bump the version once? I'm planning to bump it for https://github.com/tronikos/opower/pull/46

2023-09-13 15:11 UTC, jrigling commented
I plan to work on this today or on the weekend.

On Tue, Sep 12, 2023, 19:38 tronikos ***@***.***> wrote:

> Will you be able to address my commends soon so that I bump the version
> once? I'm planning to bump it for #46
> <https://github.com/tronikos/opower/pull/46>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tronikos/opower/pull/44#issuecomment-1716856551>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABVXRQHYOB6P4BCZBIWVRU3X2EMDVANCNFSM6AAAAAA4ODP4ME>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-17 00:50 UTC, tronikos requested changes

2023-09-17 00:50 UTC, tronikos commented on src/opower/utilities/portlandgeneral.py
> +    ) -> None:
This is failing the checks. You are returning a string

2023-09-17 01:17 UTC, jrigling commented
Comments are addressed and error messages are improved. Though I'm having trouble with the pydantic plugin for mypy. 

This was tested on my Home Assistant until Sept 15 when I updated to Home Assistant Core 2023.9.2.
Now it has these errors:
```
2023-09-16 17:56:39.240 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Portland General Electric (PGE) (username@gmail.com) for opower
File "/config/custom_components/opower/__init__.py", line 17, in async_setup_entry
coordinator = OpowerCoordinator(hass, entry.data)
File "/config/custom_components/opower/coordinator.py", line 53, in __init__
self.api = Opower(
File "/usr/local/lib/python3.11/site-packages/opower/opower.py", line 179, in __init__
File "/usr/local/lib/python3.11/site-packages/opower/opower.py", line 161, in select_utility
```
which seem unrelated to the work I have done.

2023-09-17 01:48 UTC, merged

2023-09-17 03:04 UTC, tronikos commented
I'm bumping the version in https://github.com/home-assistant/core/pull/100501
Please create a virtual integration before the next monthly HA release.